version: "3.9"

networks:
  traefik_network:
    external: true

services:
  app-dev:
    container_name: lalak-node-api-app-dev
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: lalak-node-api-app-dev
    volumes:
      - .:/var/www/html
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lalak-node-api-app-dev.rule=Host(`lalak-node-api.docker.localhost`)"
      - "traefik.http.services.lalak-node-api-app-dev.loadbalancer.server.port=3000"
      - "traefik.http.routers.lalak-node-api-app-dev.tls=true"
