export enum AbilitiesEnum {
  USERS_TECHNICAL_SUPPORT_UPDATE_STATUS = 'USERS_TECHNICAL_SUPPORT_UPDATE_STATUS',
  USERS_ADMIN_MASTER_UPDATE_STATUS = 'USERS_ADMIN_MASTER_UPDATE_STATUS',

  ADMIN_USERS_ADMIN_MASTER_VIEW = 'ADMIN_USERS_ADMIN_MASTER_VIEW',
  ADMIN_USERS_ADMIN_MASTER_INSERT = 'ADMIN_USERS_ADMIN_MASTER_INSERT',
  ADMIN_USERS_ADMIN_MASTER_UPDATE = 'ADMIN_USERS_ADMIN_MASTER_UPDATE',
  ADMIN_USERS_ADMIN_MASTER_DELETE = 'ADMIN_USERS_ADMIN_MASTER_DELETE',

  ADMIN_USERS_EMPLOYEE_VIEW = 'ADMIN_USERS_EMPLOYEE_VIEW',
  ADMIN_USERS_EMPLOYEE_INSERT = 'ADMIN_USERS_EMPLOYEE_INSERT',
  ADMIN_USERS_EMPLOYEE_UPDATE = 'ADMIN_USERS_EMPLOYEE_UPDATE',
  ADMIN_USERS_EMPLOYEE_DELETE = 'ADMIN_USERS_EMPLOYEE_DELETE',

  PROFILES_ADMIN_MASTER_VIEW = 'PROFILES_ADMIN_MASTER_VIEW',
  PROFILES_PROJECT_MANAGER_VIEW = 'PROFILES_PROJECT_MANAGER_VIEW',
  PROFILES_TEAM_LEADER_VIEW = 'PROFILES_TEAM_LEADER_VIEW',
  PROFILES_PROJECT_MEMBER_VIEW = 'PROFILES_PROJECT_MEMBER_VIEW',

  CITIES_VIEW = 'CITIES_VIEW',
  STATES_VIEW = 'STATES_VIEW',
  SYSTEM_VIEW = 'SYSTEM_VIEW',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE',

  CUSTOMERS_VIEW = 'CUSTOMERS_VIEW',
  CUSTOMERS_INSERT = 'CUSTOMERS_INSERT',
  CUSTOMERS_UPDATE = 'CUSTOMERS_UPDATE',
}
